# Generated by Django 4.2.7 on 2025-08-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AddField(
            model_name='notificacion',
            name='actividad_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='estado',
            field=models.CharField(choices=[('enviada', 'Enviada'), ('pendiente', 'Pendiente'), ('fallida', 'Fallida')], default='enviada', max_length=10),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='estudiante_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('pago_confirmado', 'Pago Confirmado'), ('pago_parcial', 'Pago Parcial'), ('recordatorio', 'Recordatorio de Pago'), ('cuota_vencida', 'Cuota Vencida'), ('nueva_cuota', 'Nueva Cuota Asignada')], max_length=20),
        ),
    ]
