# Generated by Django 4.2.7 on 2025-08-11 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_notificacion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='apoderado_email',
            field=models.EmailField(default='sin-email@ejemplo.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificacion',
            name='apoderado_nombre',
            field=models.CharField(default='Sin Nombre', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificacion',
            name='apoderado_rut',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='apoderado_telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario_registra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_registradas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
