# Generated by Django 4.2.7 on 2025-08-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_notificacion_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionsistema',
            options={},
        ),
        migrations.RenameField(
            model_name='configuracionsistema',
            old_name='email',
            new_name='email_contacto',
        ),
        migrations.RenameField(
            model_name='configuracionsistema',
            old_name='telefono',
            new_name='telefono_contacto',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='logo',
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='direccion_institucion',
            field=models.TextField(blank=True),
        ),
    ]
