# Generated by Django 5.2.5 on 2025-08-26 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_configuracionsistema_options_and_more'),
        ('estudiantes', '0002_alter_estudiante_vinculo_apoderado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='estudiante_nombre',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.estudiante'),
        ),
    ]
