# Generated by Django 4.2.7 on 2025-08-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='vinculo_apoderado',
            field=models.CharField(choices=[('hijo', 'Hijo/a'), ('padre', 'Padre'), ('madre', 'Madre'), ('abuelo', 'Abuelo/a'), ('tio', 'Tío/a'), ('tutor', 'Tutor Legal'), ('otro', 'Otro')], max_length=20),
        ),
    ]
